spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_recruitment?serverTimezone=GMT%2B8&useUnicode=true&characterEncodeing=UTF-8&useSSL=false
    username: root
    password: Mysql123
  redis:
    host: 82.157.42.25
    port: 6379
    password: Redis123
server:
  port: 3030
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  枚举类包路径
application:
  security:
    secret: caohao
  enum:
    default:
      package:
        path: com.caohao.common.enums.impl
